Testing again on node server

diff --git a/.github/workflows/gha_zadanie2.yml b/.github/workflows/gha_zadanie2.yml
--- a/.github/workflows/gha_zadanie2.yml
+++ b/.github/workflows/gha_zadanie2.yml
@@ -63,26 +63,23 @@ jobs:
       - name: Save Dcoker Scout results
         run: echo "${{ steps.scout.outputs.results }}" > scout-results.json
       
-        
       - name: Install jq
         run: sudo apt-get install -y jq
 
       - name: Check vulnerability scan results
         id: check-scan
         run: |
-          critical=$(jq -r '.critical' < scout-results.json)
-          high=$(jq -r '.high' < scout-results.json)
-          if [ "$critical" != "null" ] && [ "$high" != "null" ]; then
-            if [ "$critical" -ne 0 ] || [ "$high" -ne 0 ]; then
-              echo "Image contains critical or high vulnerabilities. Skipping push to GHCR."
-              exit 1
-            else
-              echo "No critical or high vulnerabilities found. Pushing image to GHCR."
-              echo "***" | docker login ghcr.io -u Shengan01 --password-stdin
-              docker tag shengan/zadanie_2:${{ github.sha}} ghcr.io/Shengan01/zadanie_2:${{ github.sha }}
-              docker push ghcr.io/Shengan01/zadanie_2:${{ github.sha }}
-            fi
-          else
-            echo "Unable to parse vulnerability data. Skipping push to GCR."
+          critical=$(jq '.critical' < scout-results.json)
+          high=$(jq '.high' < scout-results.json)
+          if [ -z "$critical" ] || [ -z "$high" ]; then
+            echo "Unable to parse vulnerability data. Skipping push to GHCR."
             exit 1
+          elif [ "$critical" -ne 0 ] || [ "$high" -ne 0 ]; then
+            echo "Image contains critical or high vulnerabilities. Skipping push to GHCR."
+            exit 1
+          else
+            echo "No critical or high vulnerabilities found. Pushing image to GHCR."
+            echo "***" | docker login ghcr.io -u Shengan01 --password-stdin
+            docker tag shengan/zadanie_2:${{ github.sha}} ghcr.io/Shengan01/zadanie_2:${{ github.sha }}
+            docker push ghcr.io/Shengan01/zadanie_2:${{ github.sha }}
           fi
